import React from 'react';
import { Article } from '../types';
import { X, Share2, Bookmark } from 'lucide-react';
import { LazyImage } from './LazyImage';

interface ArticleViewProps {
  article: Article;
  onClose: () => void;
  isPreview?: boolean;
}

export const ArticleView: React.FC<ArticleViewProps> = ({ article, onClose, isPreview = false }) => {
  const handleShare = async () => {
    const slug = article.title.toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const url = `${window.location.origin}/${slug}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: article.title,
          text: article.summary,
          url: url
        });
      } catch (err) {
        // User cancelled or error occurred
        console.log('Share cancelled or failed', err);
      }
    } else {
      // Fallback: copy to clipboard
      try {
        await navigator.clipboard.writeText(url);
        alert('Link copied to clipboard!');
      } catch (err) {
        console.error('Failed to copy link', err);
      }
    }
  };
  
  if (isPreview) {
    // Preview mode - show just summary and first section
    return (
      <div className="fixed inset-0 z-90 flex items-end justify-center pointer-events-none">
        <div 
          className="bg-white w-full max-w-2xl shadow-2xl border-2 border-black p-8 m-8 animate-[slideUp_0.2s_ease-out]"
          onMouseEnter={() => {}}
          onMouseLeave={() => {}}
        >
          <div className="text-xs font-mono uppercase tracking-widest text-gray-400 mb-6">
            Preview // Hover to read
          </div>
          <h2 className="text-2xl font-serif font-bold mb-4 text-ink">
            {article.title}
          </h2>
          <p className="text-gray-600 italic mb-6 leading-relaxed">
            "{article.summary}"
          </p>
          {article.sections[0] && (
            <div className="text-gray-700 mb-6">
              <h3 className="font-bold uppercase text-sm mb-2">{article.sections[0].heading}</h3>
              <p className="leading-relaxed line-clamp-4">{article.sections[0].content}</p>
            </div>
          )}
          <div className="text-center">
            <span className="text-sm font-bold text-accent">Click to read full analysis →</span>
          </div>
        </div>
      </div>
    );
  }
  
  // Full article view
  return (
    <div className="fixed inset-0 z-100 flex items-center justify-center p-4 sm:p-6">
      <div 
        className="absolute inset-0 bg-paper/95 backdrop-blur-sm"
        onClick={onClose}
      />
      
      <div className="bg-white w-full max-w-4xl max-h-[90vh] overflow-y-auto relative shadow-2xl border-2 border-black flex flex-col animate-[fadeIn_0.3s_ease-out]">
        
        {/* Modal Header */}
        <div className="sticky top-0 bg-white border-b border-gray-100 p-4 flex justify-between items-center z-10">
           <div className="text-xs font-mono uppercase tracking-widest text-gray-500">
             Generated by Journalist AI-001
           </div>
           <button 
             onClick={onClose}
             className="p-2 hover:bg-gray-100 rounded-full transition-colors"
           >
             <X size={24} />
           </button>
        </div>

        {/* Content */}
        <article className="p-8 sm:p-12 md:p-16">
          <header className="mb-12 text-center max-w-2xl mx-auto">
            <div className="inline-block bg-accent text-white px-3 py-1 text-xs font-bold uppercase tracking-widest mb-6">
              Critical Analysis
            </div>
            <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4 text-ink leading-tight">
              {article.title}
            </h1>
            <p className="text-gray-600 italic text-lg">
              "{article.summary}"
            </p>
          </header>

          {article.imageUrl && (
            <figure className="mb-12">
              <LazyImage 
                src={article.imageUrl} 
                alt={article.title}
                className="w-full h-96 object-cover rounded-lg shadow-lg"
                placeholderClassName="rounded-lg"
              />
              <figcaption className="text-center text-xs text-gray-500 mt-2">
                AI-generated imagery based on the article's topic.
              </figcaption>
            </figure>
          )}

          <div className="max-w-2xl mx-auto">
            {article.sections.map((section, index) => (
              <section key={index} className="mb-8">
                <h2 className="text-2xl font-bold font-serif text-ink mb-4 border-b-2 border-gray-100 pb-2">
                  {section.heading}
                </h2>
                <p className="text-gray-800 leading-relaxed whitespace-pre-wrap">
                  {section.content}
                </p>
              </section>
            ))}
          </div>
        </article>

        {/* Footer */}
        <footer className="sticky bottom-0 bg-white border-t border-gray-100 p-4 z-10">
          <div className="max-w-2xl mx-auto flex justify-between items-center">
            <div className="flex items-center gap-2">
              {article.tags.map((tag, index) => (
                <span key={index} className="bg-gray-100 text-gray-600 px-2 py-1 text-xs font-mono rounded">
                  #{tag}
                </span>
              ))}
            </div>
            <div className="flex items-center gap-2">
              <button onClick={handleShare} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                <Share2 size={20} />
              </button>
              <button className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                <Bookmark size={20} />
              </button>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
};
